package net.andreu.SantsMongo;

import org.bson.Document;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.*;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;

public class SampleController implements Initializable{
	@FXML
	private TextField lblNom;
	@FXML
	private Button btnNom;
	@FXML
	private ListView<String> lvNom;
	@FXML
	private TextField lblData;
	@FXML
	private Button btnData;
	@FXML
	private ListView<String> lvData;
	
	private MongoClient mongo;
	private MongoCollection<Document> coleccio;

	public void initialize(URL arg0, ResourceBundle arg1) {
		mongo = new MongoClient("localhost", 27017);
		MongoDatabase bdd = mongo.getDatabase("sants");
		coleccio = bdd.getCollection("noms");
	}
	
	// Event Listener on Button[#btnNom].onMouseClicked
	@FXML
	public void ferConsultaPerNom(MouseEvent event) {
			
		Document resultats = coleccio.find(or(eq("catala",lblNom.getText()), eq("castella", lblNom.getText()))).first();
		System.out.println(resultats);
	}
	
	// Event Listener on Button[#btnData].onMouseClicked
	@FXML
	public void ferConsultaPerData(MouseEvent event) {
		// TODO Autogenerated
	}
}
